### ISSUE TITLE
Refactor Secret Page

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#1042]
Refactor the Secrets page to have a full screen secret creation screen, like we have for create cluster.
Also, Add support for the following things:

- [ ] See when credentials were updated last (https://github.com/gardener/dashboard/issues/945)
- [ ] Show all secrets, regardless whether a secret binding with correct label exists (https://github.com/gardener/dashboard/issues/781) - do we need the label now that secretbindings have the mandatory cloud provider type field
- [ ] Add support for referencing one secret by multiple secret bindings (e.g. DNS, Infrastructure)
- [ ] Add support for creating cross-project secret bindings
- [ ] Add Handling for name clashes etc. (best thing would be to split the creation of secret bindings and secrets), see also #1301
- [ ] Merge the two secrets tables into one
