### ISSUE TITLE
[vue3] Upgrade to Vue 3

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#1418]
**What would you like to be added**:
We need to upgrade our project to Vue 3. As consequence thereof we need to upgrade Vuetify to version 3 / or switch to a diffrent UI library.
We should not only make our code work but also adapt it to the new features like composition api etc.

**Why is this needed**:
Vue 2 will reach End of Life (EOL) on December 31st, 2023

**Current Status**
- [x] https://github.com/gardener/dashboard/issues/1484
- [x] https://github.com/gardener/dashboard/issues/1483
- [x] https://github.com/gardener/dashboard/issues/1486
- [x] https://github.com/gardener/dashboard/issues/1487
- [x] https://github.com/gardener/dashboard/issues/1488
- [x] https://github.com/gardener/dashboard/issues/1485
