### ISSUE TITLE
Configure additional fields for cloud providers

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#1445]
**What would you like to be added**:
With PR #1436 we added support for adding cloud providers via dashboard configuration.
However if a cloud provider requires additional input on the cluster creation page, it is currently not possible to configure additional fields.

***Implementation Plan
- [ ] Merge https://github.com/gardener/dashboard/pull/1553
- [x] Upgrade to Vue / Vuetify 3
- [ ] Refactor `NewShootInfrastructureDetails` component to store staging resource #975
- [x] add `generic` component for additional configurable fields

As first step support only plain input fields or maybe simple dropdowns

**Why is this needed**:
Expose require or additional configuration to avoid complicated yaml editing.
