### ISSUE TITLE
Viewers should be able to access the `Shoot` cluster with read-only access

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1711]
**What would you like to be added**:
With the introduction of the [`shoots/viewerkubeconfig`](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsviewerkubeconfig-subresource) subresource, users with `Project` `viewer` role are able to request a kubeconfig with read-only access.

Viewers should be able to access the `Shoot` cluster with read-only access:

- [x] https://github.com/gardener/gardenlogin/pull/78
- [x] https://github.com/gardener/gardener/issues/9091
- [x] https://github.com/gardener/gardenctl-v2/issues/381
- [x] https://github.com/gardener/dashboard/issues/1709
- [x] https://github.com/gardener/dashboard/issues/1710

**Why is this needed**:
