### ISSUE TITLE
Cluster Labels (Admins Only)

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#33]
# Story
- As ~~operator~~ admin (the same means we use to give the operator of the week access to all projects), I want to label clusters (only visible by said admins), so that I can mark clusters as e.g. "critical" or "ignore-because-already-checked" or "performance" or "to-be-ignored".

# Motivation
Help ease the work of the operator (of the week) to drop https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operator-of-the-Week-Journal which is hard to maintain.
As long as we use the dashboard also as front-end to our self-service/canary users, we might want to hide the labels from the users. Later, this distinction and double-use (self-service and ops frontend) won't be necessary anymore and the labels can be shown to the operators in general.

# Acceptance Criteria
- [ ] Admin can set or unset cluster labels (alphabetically sorted list of single-word labels in the cluster details view, much like in GitHub)
- [ ] If cluster labels are set or unset, the action is logged into the journal (#5, much like in GitHub)
- [ ] Cluster labels are shown in the cluster list (especially #4)
- [ ] Cluster list (especially #4) can be filtered by those with certain labels or not (much like in GitHub)

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?

**Comment by vlerenc** [comment]
We will do #38 and put this ticket on ice for now.
