### ISSUE TITLE
Dashboard Tests

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#49]
Integrate tests into CI pipeline:
- [x] Backend
  - [x] Static code checks (Dashboard CI pipeline)
  - [x] Unit tests (Dashboard CI pipeline)
  - [x] Acceptance tests (Dashboard CI pipeline)
- [x] Frontend
  - [x] Static code checks (Dashboard CI pipeline)
  - [x] Unit (functional and UI component) tests (Dashboard CI pipeline)

**Comment by holgerkoser** [comment]
The end-to-end tests are not yet integrated, because it has to be discussed how to provide and kubernetes infrastructure.
* create a cluster via gardener and deploy gardener api server, etcd and dex and delete everything
* use always the same kubernetes, api server and dex and create a new namespace for each test run and delete it

**Comment by grolu** [comment]
Open Issues:
https://github.com/gardener/dashboard/issues/552
https://github.com/gardener/dashboard/issues/706

**Comment by grolu** [comment]
All tasks done.
