### ISSUE TITLE
Dashboard Extensibility

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#554]
Allow to extend the dashboard with custom add-ons, like new cloud infrastructure types without modifying the Dashboard core.
This allows operators to customize and extend the dashboard without the need for a custom build which slows down the adoption of new dashboard version.

- [X] Customize appearance (Dashboard Theming) #953 #980
- [x] Custom Cloud Providers
  - [ ] Add additional cloud providers via configuration #1434 #1553
  - [ ] Add secrets page via configuration #1553
  - [x] Customize built-in vendors #2695
  - [ ] Add additional input fields to create cluster page via configuration #1445
- [x] Introduce basic branding functionality #1568

**Comment by vlerenc** [comment]
@grolu Are more changes planned (just asking because all checkboxes are checked)?

**Comment by grolu** [comment]
The PR ist still not reviewed. But hopefully we can merge soon... Other than that there are no more changes planned.
