### ISSUE TITLE
Garden Cluster Access for End Users

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#796]
Besides control plane access for ops and shoot cluster access for project members, the latter group might also want to access the garden cluster via a web terminal, which would also have the advantage, that end users would see more prominently how K8s-native Gardener really is and that its API is actually very approachable and easy to use.

### Current Status
- [x] Decide on the Implementation Strategy (Discussion if we setup cluster for terminals or  run terminals in shoot cluster of the project) ->Decided to go with the project cluster approach
- [x] Update the Gardener Dashboard Frontend / Backend (https://github.com/gardener/dashboard/pull/852)
- [x] Update the Terminal Controller Manager, especially manage the rbac for the temporary access service account (https://github.com/gardener/terminal-controller-manager/pull/47)

**Comment by petersutter** [comment]
@vlerenc you are referring to the runtime cluster of the terminal pods, right? 
Some time ago we spoke about an (easy?/safe?) possibility to provide end-user webterminal-functionality to the garden cluster using a shared cluster. When thinking about it again I had a hard time to come up / remember "the easy and safe" solution. 

Regardless of the question on which runtime cluster (shared cluster / end-user cluster) the end-user terminals should run on, we first have to update the `terminal-controller-manager` to add some missing functionality, to have the right privileges for the (virtual) garden cluster within the terminal pod. I will post this as follow up comment and just as FYI.

**Using cluster-wide shared cluster for webterminals:**
- Protection needed against excessive usage
     - Pod limits for CPU, memory
     - Quota for network traffic. How?
     - ResourceQuota for terminal resources, see also https://github.com/gardener/terminal-controller-manager/issues/16#issuecomment-600556031, however ideally it should only affect the shared cluster
- How to restrict/allow it for different projects?
  Can we make use of secretbindings?
- How to schedule a pod on the shared cluster, to which the user does not have any access credentials?
  The validating webhook of the `terminal-controller-manager` makes sure, that anyone who creates a terminal resource and references a secret within the terminal resource, should also have the permission to read it. Otherwise the request is rejected. 
  Once the terminal resource is in a ready state, the browser will attach to the pod on the host/runtime cluster. For this the token of the temporary service account is needed, that was created by the terminal-controller-manager. This attach-service-account only has the permission to attach to a specific terminal pod (and watch the terminal pod) in the respective namespace.
  To read the token of the attach-service-account on the host cluster, the secret containing the kubeconfig of the host cluster is read (with the token of the user) in order to initialize the kubernetes client for the host cluster and to finally read the attach-token.

End-user requests terminal session for virtual garden cluster:
  Required validations:
    - User needs to be a member of the project with "admin" role
    - (A secretbinding has to exist in the project namespace pointing to the secret of the shared cluster?)

  Dashboard creates terminal resource with the dashboard's client instead of with the user's token.
  The Dashboard writes a custom annotation created-for to the terminal resource. It must be ensured that this field is immutable
  -> The dashboard needs the permission to read the secret of the shared cluster
  A fixed terminal resource will be created by the dasboard
  - host = shared cluster, temporary namespace
  - target = service account on virtual garden
  When the user requests the access-token of the host cluster, it must be read with the dashboard's client as the user does not have access to the shared cluster

**Using End-user cluster for webterminals:**

When creating a new terminal session we need to add a cluster selection component.
In addition we need to add a disclaimer that the user needs to make sure that only project-admins have cluster-admin access to the host cluster, or more precisely, only project-admins should have the permission to get secrets across all namespaces) to protect the token of the temporary service account for the garden cluster of this project.
- Disadvantage: At least one cluster required for garden cluster access.

Maybe I missed something obvious that speaks for the shared cluster, but my feeling is we are better off using the end-user cluster for the terminals, at least to start with that. Working around security concepts implemented by the `terminal-controller-manager` does not seem right, or we need to find a different way. Also I feel that it will be hard to protect ourselves from excessive usage of the shared cluster and make it bullet proof, again, maybe I oversee something.

**Comment by petersutter** [comment]
here the follow up comment as stated above, as FYI

### Manage permissions for temporary service account
**Recap**
Just to recap how the access privilege to the target cluster works:
The `Terminal` resource contains a field for the runtime/host cluster, `spec.host`, and a field for the target cluster, `spec.target`. The `terminal-controller-manager` takes the credentials (kubeconfig secret / service account) of `spec.target.credentials` to talk to the target cluster. These credentials could of course be used within the terminal pod to talk to the target cluster, but for security and audit-ability reasons the `terminal-controller-manager` creates a temporary service account for the target cluster that is cleaned up after the terminal session, which we refer to as "access" service account.

Currently it was sufficient to specify which ClusterRole and Rolebinding/ClusterRoleBinding you want to have for the temporary "access" service account, which usually was `cluster-admin`.
Also, the management of the Role/ClusterRoleBinding for the target cluster access was done by the `terminal-controller-manager` (using the referred credentials under `spec.target.credentials`).

**Missing functionality:**
Now coming to how it should work for end-user terminal sessions and what needs to be added to the `terminal-controller-manager`:
The `spec.target.credentials` for an end-user terminal session should be a service account that is a member of the project with `admin` role. (This is not a hard requirement and other configurations, like secret with kubeconfig to virtual garden cluster, different role, ... are possible but this is how we would design it in the dashboard for now.)

To be able to get/update `Project`s, get/update shoots etc., the temporary "access" service account should have the same permissions as a project member with "admin" role. As stated before the `terminal-controller-manager` manages one (1) Role/ClusterRoleBindings for the "access" service account. To have the same permissions actually multiple Role/ClusterRoleBindings are required:
  - Rolebinding to ClusterRole: `gardener.cloud:system:project-member`
  - ClusterRoleBinding to ClusterRole: `gardener.cloud:system:project-member:<project-name>`

**Problem:**
Project admins, and hence the service account referenced in `spec.target.credentials`, do not have the permission to create a ClusterRoleBinding for `gardener.cloud:system:project-member:<project-name>` which is needed e.g. to be able to get/update the `Project`.

**Solution:**
The idea is now to let `gardener` manage the Role/ClusterRoleBindings for the "access" service account. Hence the `terminal-controller-manager` would temporarily add the "access" service account as member to the project with the respective role.

**Comment by vlerenc** [comment]
@petersutter Indeed, that was the subject matter.

> Quota for network traffic. How?
See https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping.

If we have to use end user (shoot) clusters, I don't think it's worth it/fits the bill. The purpose of the garden cluster terminal would be to show people how kubernetes-native Gardener is, how easy it is to manipulate everything, etc. Asking a first-time user to first create a cluster via the dashboard seems to defy that purpose/kill that story.

If on the other hand, the effort with a shared cluster on our end is too high (no pragmatic comprise yields sufficiently low effort), then it's unrealistic that we will do it.

**Comment by grolu** [comment]
Current Status
[x] Decide on the Implementation Strategy (Discussion if we setup cluster for terminals or  run terminals in shoot cluster of the project) ->Decided to go with the project cluster approach
[x] Update the Gardener Dashboard Frontend / Backend (https://github.com/gardener/dashboard/pull/852)
[x] Update the Terminal Controller Manager, especially manage the rbac for the temporary access service account (https://github.com/gardener/terminal-controller-manager/pull/47)

**Comment by petersutter** [comment]
we can still also have a shared cluster approach, but the cheapest solution was to start with the project cluster..

**Comment by grolu** [comment]
Right, but I guess we will close this ticket and consider it as done for now. We could (if we have time and demand) go for the shared cluster approach but this is currently not planned.

**Comment by vlerenc** [comment]
Well, what a pity, but OK. It's primary a cool feature, not an essential feature. Thank you for the write-up nonetheless.

**Comment by vlerenc** [comment]
@petersutter I didn't notice after our discussion, but you did it @petersutter for end users a few days later?

**Comment by petersutter** [comment]
yes, at least using the end user clusters for the garden cluster access
