### ISSUE TITLE
Implement OIDC Token Refresh (Drop Dex)

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#976]
# Stories
- As provider I want a secure and minimal landscape setup (minimal helps with security but also with maintainability as there are fewer components). 

# Motivation
We need to implement OIDC token refresh in the Gardener Dashboard backend to support OIDC providers with short token lifetimes. This allows us to get rid of Dex for these cases. Short token lifetimes is also a preparation to get rid of cookies.

# Acceptance Criteria
- [ ] Implement OIDC token refresh #1246
- [ ] Remove Dex from charts (check with community and landscaper component) 
- [ ] Migrate from cookie to header based authentication mechanism #1259

**Comment by holgerkoser** [comment]
Move the task of removing the JWTs from cookies to localstorage into an own issue #1259.
